### ISSUE TITLE
Location(s) Delete for api/locations

### ISSUE THREAD

**Issue by rkgeorge** [Microsoft/Bing-Maps-Fleet-Tracker#1]
Is there an api for deleting existing location(s)?
swagger doesn't show delete for /api/locations ?

I also didn't see any location delete in the admin page?

**Comment by momohs** [comment]
At this point, we don't have an API for location deletion. However, it is very easy to add to the back-end. I can guide you through if you would like to add it to the code base.

**Comment by rkgeorge** [comment]
thanks - I downloaded zipped code from GitHub, but I'm having problems with build.

Using VS2017 Pro V15.1
These build individually:
  Common
  Configuration
  EntityFramework
  Func
  Models
  Repositories
  TripDetection

These do not:
  **Trackable.Services**
       66 errors ... "You must add  reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral" ...
       added ref C:\Program Files\dotnet\sdk\2.0.0\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\netstandard.dll to build Trackable.Services

**Trackable.Web** project  130 errors 
Added assemblies for:
  using Microsoft.AspNetCore.Authentication;
  using Microsoft.AspNetCore.Authentication.Cookies;
  using Microsoft.AspNetCore.Authentication.OpenIdConnect;
  using Microsoft.AspNetCore.Authorization;
  using System.Web;

reduces to 58 errors in 
  **Trackable.Web.Controllers.UsersController** 
'HttpContext' does not contain a definition for 'ChallengeAsync'
'HttpContext' does not contain a definition for 'SignOutAsync'
Note Reference added for System.Web  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Web.dll


  **Trackable.Web.Controllers.DevicesController** 
       doesn't seem to find? &lt;PackageReference Include="Microsoft.AspNetCore.SignalR" 
        Version="1.0.0-alpha2-final" /&gt;
tried Nuget uninstall/install SignalR without success.

  **Trackable.Web.Controllers.PingController** 
  **Trackable.Web.Controllers.HomeController**

**Comment by momohs** [comment]
It looks like you need to install the .Net Core 2.0 SDK. Here is a [blog post](https://blogs.msdn.microsoft.com/benjaminperkins/2017/09/20/how-to-install-net-core-2-0/) on how to install it. All you need to do is make sure your VS is updated and install the SDK binaries. Let me know if this solves your compilation issues.

Side note: cloning the repository is always better than downloading it as a zip because it would be easier for you to fetch newer versions.

**Comment by rkgeorge** [comment]
Thanks for the tip. Update to VS2017 15.5.6 fixed all my build issues.

**Comment by momohs** [comment]
Thanks @manojattal for your contribution. I'll close this issue for now. Please feel free to re-open if there are still any questions.
