### ISSUE TITLE
Using PAT to access Rest service

### ISSUE THREAD

**Issue by onterra** [Microsoft/Bing-Maps-Fleet-Tracker#11]
Below results in html login response rather than json results.
Is this the correct use of PAT for Rest Access?
<pre>
// try PAT Personal Access Token
var personalaccesstoken = "<replace with user token from user edit or 
                                               /api/users/me/token?regenerateToken=false>";

using (HttpClient client = new HttpClient())
{
	client.DefaultRequestHeaders.Accept.Add(
		new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("text/plain"));

	client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic",
		Convert.ToBase64String(
			System.Text.ASCIIEncoding.ASCII.GetBytes(
				string.Format("{0}:{1}", "", personalaccesstoken))));

	using (HttpResponseMessage message = client.GetAsync(baseAddress + restQuery).Result)
	{
		message.EnsureSuccessStatusCode();
		response.result = await message.Content.ReadAsStringAsync();
	}
}
</pre>

thanks

**Comment by momohs** [comment]
To add the token to the request, you need to send it using the "bearer" scheme as follows:

`client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", personalaccesstoken);`

**Comment by momohs** [comment]
I'll close this issue for now. Please feel free to reopen it if you still have any problem.
