### ISSUE TITLE
Issue in setting up website

### ISSUE THREAD

**Issue by manojattal** [Microsoft/Bing-Maps-Fleet-Tracker#16]
Hi,
I am trying to take a look at back-end code and wanted to fix one reported issue. I followed the steps mentioned here https://github.com/Microsoft/Bing-Maps-Fleet-Tracker/blob/master/Backend/README.md

1. I went to https://apps.dev.microsoft.com and created an app. Updated Authorization.ClientId, Authorization.ClientSecret from this. Provided Authorization.OwnerEmail as my email.
2. There was no information about what should be Authorization.SecurityKey. I just went to https://randomkeygen.com/ and used one of "128-bit WEP Keys" from there.
3. I went to https://www.bingmapsportal.com. Created an application and updated value of SubscriptionKeys.BingMaps
4. Built front end code and copied files at path "Backend\src\Trackable.Web\wwwroot\dist"
5. Now when I run project, localhost:portno/locations, bing map show error "Specified credentials are invalid" and cosnole tab shows following errors.

zone.js:2933 GET http://localhost:4488/api/users/me 0 ()
scheduleTask @ zone.js:2933
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:411
onScheduleTask @ zone.js:301
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:405
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2966
proto.(anonymous function) @ zone.js:1366
(anonymous) @ http.es5.js:1275
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable._trySubscribe @ Observable.js:172
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ Observable.js:160
webpackJsonp.../../../../../src/app/core/authorized-http.service.ts.AuthorizedHttpService.get @ authorized-http.service.ts:18
webpackJsonp.../../../../../src/app/core/data.service.ts.DataService.getSingle @ data.service.ts:63
webpackJsonp.../../../../../src/app/users/auth.service.ts.AuthService.getLoggedInUser @ auth.service.ts:21
webpackJsonp.../../../../../src/app/users/auth.service.ts.AuthService.loginOrGetUser @ auth.service.ts:28
webpackJsonp.../../../../../src/app/users/login/login.component.ts.LoginComponent.ngOnInit @ login.component.ts:37
checkAndUpdateDirectiveInline @ core.es5.js:10843
checkAndUpdateNodeInline @ core.es5.js:12341
checkAndUpdateNode @ core.es5.js:12284
debugCheckAndUpdateNode @ core.es5.js:13141
debugCheckDirectivesFn @ core.es5.js:13082
(anonymous) @ AppComponent.html:5
debugUpdateDirectives @ core.es5.js:13067
checkAndUpdateView @ core.es5.js:12251
callViewAction @ core.es5.js:12599
execComponentViewsAction @ core.es5.js:12531
checkAndUpdateView @ core.es5.js:12257
callWithDebugContext @ core.es5.js:13467
debugCheckAndUpdateView @ core.es5.js:13007
webpackJsonp.../../../core/@angular/core.es5.js.ViewRef_.detectChanges @ core.es5.js:10174
(anonymous) @ core.es5.js:4812
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick @ core.es5.js:4812
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_._loadComponent @ core.es5.js:4787
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.bootstrap @ core.es5.js:4775
(anonymous) @ core.es5.js:4546
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._moduleDoBootstrap @ core.es5.js:4546
(anonymous) @ core.es5.js:4508
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
(anonymous) @ zone.js:873
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:425
onInvokeTask @ core.es5.js:3881
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:424
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
Promise.then (async)
scheduleMicroTask @ zone.js:585
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:414
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:871
ZoneAwarePromise.then @ zone.js:981
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4537
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule @ core.es5.js:4522
../../../../../src/main.ts @ main.ts:12
__webpack_require__ @ bootstrap de442838fa44fd958ee7:54
0 @ main.bundle.js:6434
__webpack_require__ @ bootstrap de442838fa44fd958ee7:54
webpackJsonpCallback @ bootstrap de442838fa44fd958ee7:25
(anonymous) @ main.bundle.js:1
core.es5.js:1020 ERROR Response {_body: ProgressEvent, status: 0, ok: false, statusText: "", headers: Headers, …}headers: Headers {_headers: Map(0), _normalizedNames: Map(0)}ok: falsestatus: 0statusText: ""type: 3url: null_body: ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: "error", …}__proto__: Body
defaultErrorLogger @ core.es5.js:1020
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1080
next @ core.es5.js:4503
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:239
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.next @ Subscriber.js:186
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber._next @ Subscriber.js:127
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next @ Subscriber.js:91
webpackJsonp.../../../../rxjs/_esm5/Subject.js.Subject.next @ Subject.js:56
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
(anonymous) @ core.es5.js:3912
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.runOutsideAngular @ core.es5.js:3844
onHandleError @ core.es5.js:3912
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:396
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:195
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
error (async)
customScheduleGlobal @ zone.js:1666
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:411
onScheduleTask @ zone.js:301
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:405
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleEventTask @ zone.js:262
(anonymous) @ zone.js:1832
(anonymous) @ http.es5.js:1274
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable._trySubscribe @ Observable.js:172
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ Observable.js:160
webpackJsonp.../../../../../src/app/core/authorized-http.service.ts.AuthorizedHttpService.get @ authorized-http.service.ts:18
webpackJsonp.../../../../../src/app/core/data.service.ts.DataService.get @ data.service.ts:29
webpackJsonp.../../../../../src/app/assets/asset.service.ts.AssetService.getAssets @ asset.service.ts:22
webpackJsonp.../../../../../src/app/assets/asset-list/asset-list.component.ts.AssetListComponent.ngOnInit @ asset-list.component.ts:53
checkAndUpdateDirectiveInline @ core.es5.js:10843
checkAndUpdateNodeInline @ core.es5.js:12341
checkAndUpdateNode @ core.es5.js:12284
debugCheckAndUpdateNode @ core.es5.js:13141
debugCheckDirectivesFn @ core.es5.js:13082
(anonymous) @ AssetListComponent_Host.html:1
debugUpdateDirectives @ core.es5.js:13067
checkAndUpdateView @ core.es5.js:12251
callViewAction @ core.es5.js:12599
execEmbeddedViewsAction @ core.es5.js:12557
checkAndUpdateView @ core.es5.js:12252
callViewAction @ core.es5.js:12599
execComponentViewsAction @ core.es5.js:12531
checkAndUpdateView @ core.es5.js:12257
callWithDebugContext @ core.es5.js:13467
debugCheckAndUpdateView @ core.es5.js:13007
webpackJsonp.../../../core/@angular/core.es5.js.ViewRef_.detectChanges @ core.es5.js:10174
(anonymous) @ core.es5.js:4812
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick @ core.es5.js:4812
(anonymous) @ core.es5.js:4684
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.run @ core.es5.js:3821
next @ core.es5.js:4684
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:239
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.next @ Subscriber.js:186
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber._next @ Subscriber.js:127
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next @ Subscriber.js:91
webpackJsonp.../../../../rxjs/_esm5/Subject.js.Subject.next @ Subject.js:56
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
checkStable @ core.es5.js:3855
onHasTask @ core.es5.js:3903
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:445
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:465
webpackJsonp.../../../../zone.js/dist/zone.js.Zone._updateTaskCount @ zone.js:289
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:209
drainMicroTaskQueue @ zone.js:602
Promise.then (async)
scheduleMicroTask @ zone.js:585
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:414
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:871
ZoneAwarePromise.then @ zone.js:981
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4537
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule @ core.es5.js:4522
../../../../../src/main.ts @ main.ts:12
__webpack_require__ @ bootstrap de442838fa44fd958ee7:54
0 @ main.bundle.js:6434
__webpack_require__ @ bootstrap de442838fa44fd958ee7:54
webpackJsonpCallback @ bootstrap de442838fa44fd958ee7:25
(anonymous) @ main.bundle.js:1
zone.js:2933 GET http://localhost:4488/api/settings/subscriptionkeys 0 ()
scheduleTask @ zone.js:2933
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:411
onScheduleTask @ zone.js:301
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:405
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2966
proto.(anonymous function) @ zone.js:1366
(anonymous) @ http.es5.js:1275
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable._trySubscribe @ Observable.js:172
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ Observable.js:160
webpackJsonp.../../../../../src/app/core/authorized-http.service.ts.AuthorizedHttpService.get @ authorized-http.service.ts:18
webpackJsonp.../../../../../src/app/core/data.service.ts.DataService.getNoCache @ data.service.ts:43
webpackJsonp.../../../../../src/app/core/settings.service.ts.SettingsService.getSubscriptionKey @ settings.service.ts:25
webpackJsonp.../../../../../src/app/maps/maps/maps.component.ts.MapsComponent.ngOnInit @ maps.component.ts:25
checkAndUpdateDirectiveInline @ core.es5.js:10843
checkAndUpdateNodeInline @ core.es5.js:12341
checkAndUpdateNode @ core.es5.js:12284
debugCheckAndUpdateNode @ core.es5.js:13141
debugCheckDirectivesFn @ core.es5.js:13082
(anonymous) @ AppComponent.html:23
debugUpdateDirectives @ core.es5.js:13067
checkAndUpdateView @ core.es5.js:12251
callViewAction @ core.es5.js:12599
execEmbeddedViewsAction @ core.es5.js:12557
checkAndUpdateView @ core.es5.js:12252
callViewAction @ core.es5.js:12599
execComponentViewsAction @ core.es5.js:12531
checkAndUpdateView @ core.es5.js:12257
callWithDebugContext @ core.es5.js:13467
debugCheckAndUpdateView @ core.es5.js:13007
webpackJsonp.../../../core/@angular/core.es5.js.ViewRef_.detectChanges @ core.es5.js:10174
(anonymous) @ core.es5.js:4812
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick @ core.es5.js:4812
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_._loadComponent @ core.es5.js:4787
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.bootstrap @ core.es5.js:4775
(anonymous) @ core.es5.js:4546
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._moduleDoBootstrap @ core.es5.js:4546
(anonymous) @ core.es5.js:4508
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
(anonymous) @ zone.js:873
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:425
onInvokeTask @ core.es5.js:3881
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:424
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
Promise.then (async)
scheduleMicroTask @ zone.js:585
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:414
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:871
ZoneAwarePromise.then @ zone.js:981
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4537
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule @ core.es5.js:4522
../../../../../src/main.ts @ main.ts:12
__webpack_require__ @ bootstrap de442838fa44fd958ee7:54
0 @ main.bundle.js:6434
__webpack_require__ @ bootstrap de442838fa44fd958ee7:54
webpackJsonpCallback @ bootstrap de442838fa44fd958ee7:25
(anonymous) @ main.bundle.js:1
maps.component.ts:162 Response {_body: ProgressEvent, status: 0, ok: false, statusText: "", headers: Headers, …}headers: Headers {_headers: Map(0), _normalizedNames: Map(0)}ok: falsestatus: 0statusText: ""type: 3url: null_body: ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: "error", …}bubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: XMLHttpRequest {readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, responseURL: "", …}defaultPrevented: falseeventPhase: 0isTrusted: truelengthComputable: falseloaded: 0path: []returnValue: truesrcElement: XMLHttpRequest {readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, responseURL: "", …}target: XMLHttpRequest {readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, responseURL: "", …}timeStamp: 15756.89999999986total: 0type: "error"__proto__: ProgressEvent__proto__: Body
zone.js:2933 GET http://localhost:4488/api/assets 0 ()
scheduleTask @ zone.js:2933
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:411
onScheduleTask @ zone.js:301
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:405
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2966
proto.(anonymous function) @ zone.js:1366
(anonymous) @ http.es5.js:1275
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable._trySubscribe @ Observable.js:172
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ Observable.js:160
webpackJsonp.../../../../../src/app/core/authorized-http.service.ts.AuthorizedHttpService.get @ authorized-http.service.ts:18
webpackJsonp.../../../../../src/app/core/data.service.ts.DataService.get @ data.service.ts:29
webpackJsonp.../../../../../src/app/assets/asset.service.ts.AssetService.getAssets @ asset.service.ts:22
webpackJsonp.../../../../../src/app/assets/asset-list/asset-list.component.ts.AssetListComponent.ngOnInit @ asset-list.component.ts:53
checkAndUpdateDirectiveInline @ core.es5.js:10843
checkAndUpdateNodeInline @ core.es5.js:12341
checkAndUpdateNode @ core.es5.js:12284
debugCheckAndUpdateNode @ core.es5.js:13141
debugCheckDirectivesFn @ core.es5.js:13082
(anonymous) @ AssetListComponent_Host.html:1
debugUpdateDirectives @ core.es5.js:13067
checkAndUpdateView @ core.es5.js:12251
callViewAction @ core.es5.js:12599
execEmbeddedViewsAction @ core.es5.js:12557
checkAndUpdateView @ core.es5.js:12252
callViewAction @ core.es5.js:12599
execComponentViewsAction @ core.es5.js:12531
checkAndUpdateView @ core.es5.js:12257
callWithDebugContext @ core.es5.js:13467
debugCheckAndUpdateView @ core.es5.js:13007
webpackJsonp.../../../core/@angular/core.es5.js.ViewRef_.detectChanges @ core.es5.js:10174
(anonymous) @ core.es5.js:4812
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick @ core.es5.js:4812
(anonymous) @ core.es5.js:4684
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.run @ core.es5.js:3821
next @ core.es5.js:4684
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:239
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.next @ Subscriber.js:186
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber._next @ Subscriber.js:127
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next @ Subscriber.js:91
webpackJsonp.../../../../rxjs/_esm5/Subject.js.Subject.next @ Subject.js:56
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
checkStable @ core.es5.js:3855
onHasTask @ core.es5.js:3903
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:445
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:465
webpackJsonp.../../../../zone.js/dist/zone.js.Zone._updateTaskCount @ zone.js:289
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:209
drainMicroTaskQueue @ zone.js:602
Promise.then (async)
scheduleMicroTask @ zone.js:585
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:414
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:871
ZoneAwarePromise.then @ zone.js:981
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4537
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule @ core.es5.js:4522
../../../../../src/main.ts @ main.ts:12
__webpack_require__ @ bootstrap de442838fa44fd958ee7:54
0 @ main.bundle.js:6434
__webpack_require__ @ bootstrap de442838fa44fd958ee7:54
webpackJsonpCallback @ bootstrap de442838fa44fd958ee7:25
(anonymous) @ main.bundle.js:1
zone.js:2933 GET http://localhost:4488/api/locations 0 ()

6. When I browse "http://localhost:42484/api/locations", it shows HTTP ERROR 401. And Locations controller does not get hit in debugger.

Can you help what am I missing here?

**Comment by manojattal** [comment]
Hi @momohs 

Thanks for help. Yes, front-end was not built with that parameter. I rebuilt front end and replaced files in wwwroot. Now after running the application, it is redirecting on signin page. But my after entering liveid credentials I see below error in URL. Did I miss something?

https://login.live.com/err.srf?lc=1033#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application.&state=CfDJ8DN05om7FBhGmQ5716U4e-g--w_pLgzx0Pf1w5RC0uykQZ19Db1dEJBFemzZN8MwqOQ_CpLWKfbAaWKNlsiBo4iI2pSF-t74NdYyMN_eR-bcB-reoHA4Vc-dzCua6wemMefSSNpUZpTp48XEmVQcCnh5FPeqNZiVcZyPEbuvSCB1pr2d7Rh-B4gOpY-wfNsXJPp1XvYG_xT0lXGnw2NOFTTpG-CW23mB624asyi_jAA6b8NtrvRRhq-Zr4yah2O2ERpTksc0VaMxpqdn-vdIKw4ubIpCAQbHzJxT0jlHFAuJU3iMMOP5Oc2ojn0DTNgA25b7nQpQyNZ47oUEkD_cVBw

**Comment by momohs** [comment]
The problem is in your authorization application (created through  https://apps.dev.microsoft.com), you need to add the reply URL "[http://localhost:<port_number>/signin-oidc](http://localhost:<port_number>/signin-oidc)" to your application.

The documentation needs to be updated to clarify the issues that you've faced. Would you like to update it?

**Comment by V4ka** [comment]
@manojattal 
Go to https://apps.dev.microsoft.com. For created app add Web Platform. Insert Redirect URL as @momohs advised:
![redirect url](https://user-images.githubusercontent.com/28557071/36553809-bf8bda4e-1816-11e8-82cb-b22b2caef491.jpg)

**Comment by manojattal** [comment]
@momohs sure, I will update docs with issues that I am facing.
I added redirect URL. Now I have moved on to next error :)

Now I am getting redirected to "http://localhost:42484/api/users/accessdenied"

Access to localhost was denied
You don't have authorization to view this page.
HTTP ERROR 403

Can you help to figure out what should be missing?

**Comment by momohs** [comment]
I would need some more context on how to reproduce this error. If you try going to http://localhost:42484 does the portal load? Are you able to sign in and successfully get redirected to the portal?

**Comment by manojattal** [comment]
Yes, portal gets loaded. It asks me to sign-in. After I provide my credentials, it gets redirected to url "http://localhost:42484/api/users/accessdenied"

[https://imgur.com/bbr3ApJ](url)

**Comment by momohs** [comment]
I am unable to reproduce this on my machine. Would be great if you place a breakpoint in the `OnAuthenticationFailed` function in the Startup.cs file and give us more information about the failure reason. The reason should be found in the `RemoteFailureContext context` parameter.

**Comment by manojattal** [comment]
This is the error that it is giving in RemoteFailureContext.
"IDX10214: Audience validation failed. Audiences: '00000000-0000-0000-0000-000044206684'. Did not match: validationParameters.ValidAudience: '0000000044206684' or validationParameters.ValidAudiences: 'null'."

Value in appsetting.json is "ClientId": "0000000044206684", and Bing maps application Id is "0000000044206684". I am not sure from where is it adding so many zeroes to ID.

**Comment by momohs** [comment]
It seems like your client ID is not setup correctly, it should be set to the value of the application ID you get for your application on https://apps.dev.microsoft.com.

**Comment by manojattal** [comment]
Yeah, setting client ID to long client ID received in earlier error message fixed my issue. Thanks!
