### ISSUE TITLE
SecurityKey in appsettings.json file

### ISSUE THREAD

**Issue by dnjoroge55** [Microsoft/Bing-Maps-Fleet-Tracker#2]
How or where can I get the Security Key? 

appsettings.json file
"Authorization": {
    "ClientId": "",
    "ClientSecret": "",
    "OwnerEmail": "",
    "SecurityKey": "???"
  },

**Comment by momohs** [comment]
This key is used to sign JWT tokens. As mentioned in the [README](https://github.com/Microsoft/Bing-Maps-Fleet-Tracker#rest-service-build-and-run) it is a string of at-least 128bits that is 16 characters. Any Random GUID would work as well.

**Comment by momohs** [comment]
I'll close this issue for now. Please feel free to re-open if you still have any problem.
