### ISSUE TITLE
Tracking doesn't work with only a device record?

### ISSUE THREAD

**Issue by stevemilroy** [Microsoft/Bing-Maps-Fleet-Tracker#34]
Seems like we need to add an asset mapped to device to get tracking to start?

**Comment by momohs** [comment]
Yes, the device has to be mapped to an asset for tracking to work. Since this is an asset tracking solution, we track assets using devices. We don't store points for devices that are not assigned to assets.

**Comment by momohs** [comment]
I'll close this issue for now. Please feel free to reopen it if you still have any questions.
