### ISSUE TITLE
purging old locations from the DB

### ISSUE THREAD

**Issue by onterra** [Microsoft/Bing-Maps-Fleet-Tracker#36]
We are having trouble locating the password for the Hurghada DB generated by the auto deployment. We want to purge some of the old positions in order to demo Microsoft FleetTracker to some of our clients. Does the password default to the subscription password?
If we change the password using the Azure portal will that affect access for the existing deployment REST services?

It would be helpful to add datetime filtering to the REST queries. As time goes on there are large numbers of positions that are returned by the REST queries, that then need to be filtered for datetime either in a proxy server or on the client. It would be more efficient to have a FromDate and ToDate query parameter in the sql stored procedure backend.

Thanks

**Comment by momohs** [comment]
The whole connection string can be seen from the "Application Settings" of your "App Service" in the Azure portal. It is under the name "connectionStrings__DefaultConnection". If you change the DB password, please note that the Application Settings will be reset while updating your deployment.

The datetime filtering makes perfect sense, we will add it to our backlog. Thanks for your suggestion.

**Comment by momohs** [comment]
I'll close this issue for now. Please feel free to reopen it if you still have any questions.
