### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by stevemilroy** [Microsoft/Bing-Maps-Fleet-Tracker#4]
Is there any end user documentation on features apart from the few sections in the readme? Related to this, we are not clear on how the trips/dispatching features should work?

**Comment by momohs** [comment]
At this point, all the documentation we have is in the readme file.

Regarding the trips/dispatching, for now, it displays the routes for cars/trucks on the UI. However, it is not yet integrated with the mobile device.

**Comment by stevemilroy** [comment]
Thanks, we haven't been able to get trips to work and there is no data in the reports etc. Can you describe step to step how to get it to work?

**Comment by momohs** [comment]
Trip detection logic should run every around 30 mins. If you've done your deployment through the deployment portal, can you try the following:
1. Open the deployment portal and enter your deployment name
2. A prompt should appear saying "Open update page", click it
3. The update page should have all your deployment parameters pre-populated, do not change anything
4. Re-deploy/update your app - this will not delete any of your data but will attempt to fix the deployment.

Let me know if this solves it for you

**Comment by stevemilroy** [comment]
Yes, this worked to fix the problem. Thanks

**Comment by momohs** [comment]
Will close this issue for now. Please feel free to re-open if you still have any questions.
