### ISSUE TITLE
Backend\Trackable.sln does not build

### ISSUE THREAD

**Issue by wvmstr** [Microsoft/Bing-Maps-Fleet-Tracker#41]
Severity	Code	Description	Project	File	Suppression State	Line
Error	CS0006	Metadata file 'C:\Repos\FleetTrckr\Bing-Maps-Fleet-Tracker-master\Backend\src\Trackable.EntityFramework\bin\Debug\Trackable.EntityFramework.dll' could not be found	Trackable.Repositories	C:\Repos\FleetTrckr\Bing-Maps-Fleet-Tracker-master\Backend\src\Trackable.Repositories\CSC	Active	1

Plus 15 more (Trackable.): Repositories.dll, EntityFramework.dll,  etc.

And:
Severity	Code	Description	Project	File	Suppression State	Line
Error		Cannot evaluate the item metadata "%(FileName)". The item metadata "%(FileName)" cannot be applied to the path "C:\Repos\FleetTrckr\Bing-Maps-Fleet-Tracker-master\Backend\src\Trackable.EntityFramework\..\..\packages\Microsoft.Extensions.DependencyInjection.Abstractions.2.0.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.	Trackable.EntityFramework

**Comment by wvmstr** [comment]
That did the trick. May I suggest to reduce the name of the folder "Bing-Maps-Fleet-Tracker-master" to simply master in the package.

**Comment by MustafaLeithy** [comment]
The zip name is auto-generated by Github as "{repository name}-{branch name}". We have no control over this.

I am closing this issue. Feel free to re-open if you run into further problems.
