### ISSUE TITLE
Frontend not available in mobile devices

### ISSUE THREAD

**Issue by rcandil** [Microsoft/Bing-Maps-Fleet-Tracker#43]
Hi. I deployed an instance using the one click webpage successfully. However if I try to access the frontend using my mobile device i.e. iPhone the webpage does keep in loading animated icon for ever and never goes into the portal. It happens while using safari and chrome for iOS. It also happens in chrome in Abdroid devices. Can this be fixed?

**Comment by momohs** [comment]
We have seen such issues with old browsers. Which iOS version are you using?

**Comment by rcandil** [comment]
Hi. 

I'm using 10.3.3 on my iPhone. Issue also happens on Chrome for iOS, which is up to date in this same device. 

Thanks for your prompt answer.

**Comment by wvmstr** [comment]
I can confirm it works from a Galaxy Note and a Pixel XL.

Can you log in from a Windows machine?

**Comment by rcandil** [comment]
Issues had to do with older device. Closing.
