### ISSUE TITLE
Trips / TripLegs tables are not being populated

### ISSUE THREAD

**Issue by wvmstr** [Microsoft/Bing-Maps-Fleet-Tracker#44]
None of my trip related reports show any data.  Show latest trips does not show anything either.

Looking in the db I see that tables Trips and TripLegs are empty.

**Comment by MustafaLeithy** [comment]
Do your assets show points when you click "Show Points"? 

If the answer is Yes and you still don't see any trips, then you will need to check to see if your Trip Detection is running.

1. Go to your Azure Portal
1. Find the Function App deployed with the name `{YOUR_DEPLOYMENT_NAME}Func`
1. Check under the 'Functions' tab. You should see two functions named `PipelineInitiator` and `PipelineExecutor`. These are responsible for the trip detection.
1. If the 'Functions' tab is empty, then you will have to redeploy the Function App.

To re-deploy the function app:
1. Go to the [Bing Maps Fleet Tracker Deployment Portal](https://aka.ms/bingmapsfleettracker).
1. Sign in with the account you have your Azure subscription and deployment on. If you have multiple Azure subscriptions you will need to specify the one your deployment exists on.
1. Enter the name of your deployment in the Deployment Name field. You should receive a prompt pointing you to an update link. Click on the update link. You will be redirected to the update page.
1. Your deployment secrets that you entered previously will be pre-populated with their old values. Click the Deploy button and wait until the deployment finishes. This will not create a new deployment, but will update your existing one.

You should probably check again after the deployment finishes to make sure that your trip detection is running. You should notice that your assets have trips now, assuming they had tracked points.

**Comment by wvmstr** [comment]
Those two functions were not included included when I did the first deployment. Now they are there and some of those reports are being populated.

**Comment by MustafaLeithy** [comment]
We have seen this happen before, will add it to the troubleshooting section.
Closing this issue for now.
