### ISSUE TITLE
Functionality of the Android app - the two icons

### ISSUE THREAD

**Issue by wvmstr** [Microsoft/Bing-Maps-Fleet-Tracker#45]
I am eager to understand what the two icons mean that are revealed when clicking on the Bing Maps icon.

One I would call a target / location icon, the other is a marker?

What are they supposed to do?

**Comment by MustafaLeithy** [comment]
>  target / location icon
The first one zooms in to your current location.

> the other is a marker
The second one toggles between showing and hiding the tracked points on the map. 

If you have ideas for new buttons or improvements to the existing ones, you are welcome to contribute them!

**Comment by wvmstr** [comment]
I would like to contribute but already spend more than a day wading through angular, bash, yarn, node. With nothing to show for it.  The hurdle to get it into VS is too big for me. You could say I spend a day in Dependency Hell.

Anyway, I am left trying to understand the design intent of the application, which is not an easy task either. There are very few clues, but there is missing functionality, broken functionality.

**Comment by MustafaLeithy** [comment]
Code documentation is a high priority item for us that we should be tackling soon. This will make it easier for new comers to contribute effectively. 

> but there is missing functionality, broken functionality.
If you can keep compile a list with all the functionalities that you think are broken or missing that will be a great help!
