### ISSUE TITLE
Points API call does not insert points into the SQL database

### ISSUE THREAD

**Issue by rbenji23** [Microsoft/Bing-Maps-Fleet-Tracker#49]
I am trying to use a non-cell device to post api calls to the api/devices/1234/points. I get the 200 response but no point shows up in the TrackingPoints table. I have seen a few error around the TripId field, is there way to completely disable the trip detection? I just want singular points.

**Comment by momohs** [comment]
I'm assuming this issue is resolved by now. Please feel free to reopen if you're still facing the same problem.
