### ISSUE TITLE
Users?

### ISSUE THREAD

**Issue by stevemilroy** [Microsoft/Bing-Maps-Fleet-Tracker#5]
What is the purpose of users? Seems like only the admin LiveID can access the UI?

**Comment by momohs** [comment]
There are different user roles Owner, Administrator, Viewer. When a deployment is first made, the owner is set. After a new user tries signing in, they are automatically set to the role "Pending" and an administrator or owner should go to the users tab and change their role.

Administrators have more privileges than Viewers and Owners have more privileges than administrators.

**Comment by stevemilroy** [comment]
Thanks, so the email address needs to match their LiveID to login to the admin portal?

**Comment by momohs** [comment]
It doesn't matter which email you use, as long as you can login, you're good to go. However, roles are tied with emails.

**Comment by momohs** [comment]
I will close this issue for now. Please feel free to re-open if you still have any questions.
