### ISSUE TITLE
Tracking via azurewebsites.net not showing device/asset

### ISSUE THREAD

**Issue by plecomp** [Microsoft/Bing-Maps-Fleet-Tracker#51]
I followed through the walkthrough and managed to setup the maps fleet tracker and connected it successfully to my device. I have created an Asset and linked it with my device. 

On the device itself it appears that the tracking is working as I can see the devices location on the map. But am unable to see the device via the azurewebsites.net website. When I click on my device (named Truck), in the top right hand corner of the map I get a pop up that says "Can't find position of Truck". With that said, the GPS location on my device is set to high. Have tried both on a SIM and via WiFi without any difference. 

Unsure where to go from here. Any help would be greatly appreciated.

**Comment by plecomp** [comment]
Yes, as I mentioned above.  I have created an Asset and linked it with my device.

**Comment by plecomp** [comment]
Thanks for the suggestion. I believe the mobile app is the latest. Version 1.2.0.

I have enabled logging, is there a particular log file I should be looking for? I've not had to go through the logs before. I've jumped into the site via FTP but see there are a few folders and files in the LogFiles folder.

**Comment by MustafaLeithy** [comment]
You can just use the log stream option to view the logs real time in the Azure portal. You can use this [quick guide](https://www.michaelcrump.net/azure-tips-and-tricks30/). 

Once you have the log streaming working, you can just restart your mobile app and it will attempt to send points to your back end. If that operation fails, you will see an exception and a stack trace in the logs.

**Comment by plecomp** [comment]
Right, thanks for that. I did come across that, but the log itself looks pretty scrambled. I notice when I attempt to track the device through azurewebsites.net it shows in the logs but does not seem to show an error from what I can see. 

I have attached the log file. Please note that I removed my IP from the log and actual website name.

[log.txt](https://github.com/Microsoft/Bing-Maps-Fleet-Tracker/files/2221553/log.txt)

**Comment by plecomp** [comment]
So I setup my phone as a device and this appears to show in the website. Looks to be an issue with the tablet I was testing the app on. Looks like this issue is now solved! 

Is there a way to remove old devices? All I see is an Edit or location marker.

**Comment by momohs** [comment]
Deleting a device is not currently available from the front-end. However, it can be done through the REST APIs https://github.com/Microsoft/Bing-Maps-Fleet-Tracker/blob/master/WALKTHROUGH.md#using-the-rest-apis

The API implementation can be found here: https://github.com/Microsoft/Bing-Maps-Fleet-Tracker/blob/master/Backend/src/Trackable.Web/Controllers/DevicesController.cs#L258

**Comment by Rasmi91** [comment]
I'm facing the same issue.. my device/asset is not showing in local. I have added my phone manually and linked to asset. Its not showing in the map. 
I have tried to scan the qr code .Getting this json content. 
{"BaseUrl":"http://localhost:52694","RegistrationUrl":"http://localhost:52694/api/devices?nonce=838cbbb2-d7c6-a5e9-9dad-43a8451a2088","RegistrationToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQW5vbnltb3VzIiwiaXNzIjoiUHJvamVjdEh1cmdoYWRhIiwianRpIjoiNzc4YTczODYtYTg0OS00NWRkLTg4OTYtMjYwMjRmM2U2ODc5IiwiYXVkIjoiUmVnaXN0cmF0aW9uIiwiZXhwIjoiMTU0MDgwMjI3NyIsIm5iZiI6IjE1NDA4MDEzNzcifQ.dR_MJXd5gZNreXAmTWXVKhSEo-eSX9MreRLVFLKZvxs";}
Please help me to solve this issue
