### ISSUE TITLE
Trips not populating

### ISSUE THREAD

**Issue by plecomp** [Microsoft/Bing-Maps-Fleet-Tracker#52]
Trips aren't showing. I can see the position and the points for my device/asset but if i click on trips I get the pop up saying "showing latest trips of Truck" but nothing shows on the map.

I saw a previous issue listed which pointed to the issue being caused by the initial deployment. I have followed the steps in that post and in Azure can see PipelineExecutor and PipelineInitiator are there, so am not sure where to go from here as it was not listed in the previous post.

I have also tried updating the deployment as per https://github.com/Microsoft/Bing-Maps-Fleet-Tracker/issues/4 which does not seemed to have picked up the points from today.

**Comment by plecomp** [comment]
Sorry, I believe I jumped the gun on this one. It appears the trip has been populated but a day after the actual trip. I was under the impression that the trips would be populated as the device/asset is making a trip. Is this not the case?

**Comment by momohs** [comment]
The trip detection logic should run every 30 mins.

**Comment by MustafaLeithy** [comment]
Additionally the trip detection logic waits until the trip is over to show it as a trip. So it will not show a trip while you are currently driving, but rather when you reach your destination.
