### ISSUE TITLE
ASP MVC version? fleet routing/planning

### ISSUE THREAD

**Issue by papyr** [Microsoft/Bing-Maps-Fleet-Tracker#55]
Its strange that an Microsoft app, does not have an ASP MVC version.

It would be nice to have fleet routing/dispatch sample included

**Comment by IoTGirl** [comment]
Fleet Tracker is not a routing sample but I do recommend that you look at https://www.microsoft.com/en-us/maps/truck-routing to get an overview of some of our routing options
