### ISSUE TITLE
 Insufficient permission error in bing map fleet tracker hosted site

### ISSUE THREAD

**Issue by Rasmi91** [Microsoft/Bing-Maps-Fleet-Tracker#57]
Hi

Deployment was success. But getting insufficient permission error in bing map hosted site.How to solve this issue? 
![image](https://user-images.githubusercontent.com/42572707/46534606-5500dd80-c8c6-11e8-8893-a6a63697b856.png)

![image](https://user-images.githubusercontent.com/42572707/46534715-ce98cb80-c8c6-11e8-8465-ce64ffebefae.png)

**Comment by larrywelch** [comment]
I'm having the same problem but I'm not sure the screen shot above is helpful.

**Comment by momohs** [comment]
Make sure you are logged in using the same email used to deploy the solution.
