### ISSUE TITLE
Unable to register mobile devices using qr code

### ISSUE THREAD

**Issue by Rasmi91** [Microsoft/Bing-Maps-Fleet-Tracker#62]
when i was trying to register my device using qr code, i got this following  json content from qr reader app. RegistrationUrl is not working. Manual registration is not showing the current location of device. How to register the device?

{"BaseUrl":"http://localhost:52694","RegistrationUrl":"http://localhost:52694/api/devices?nonce=838cbbb2-d7c6-a5e9-9dad-43a8451a2088","RegistrationToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQW5vbnltb3VzIiwiaXNzIjoiUHJvamVjdEh1cmdoYWRhIiwianRpIjoiNzc4YTczODYtYTg0OS00NWRkLTg4OTYtMjYwMjRmM2U2ODc5IiwiYXVkIjoiUmVnaXN0cmF0aW9uIiwiZXhwIjoiMTU0MDgwMjI3NyIsIm5iZiI6IjE1NDA4MDEzNzcifQ.dR_MJXd5gZNreXAmTWXVKhSEo-eSX9MreRLVFLKZvxs";}

**Comment by momohs** [comment]
This will not work if you're running the code locally (not hosted on a server). Because your mobile cannot communicate with http://localhost:52694. Try deploying it to a server and everything should work fine.

**Comment by Rasmi91** [comment]
Thanks for your reply. I have faced the same problem in azurewebsites.net also(online deoployment from binmapportal)

**Comment by Rasmi91** [comment]
Hi As per your solution ,i hosted my site to server.But still im facing the same issue. when i was scanned the qr code i got this json content.when i was trying to access the registration url ,getting [] square box as output.Unable to detect the current location of mobile in manual registeration also.Please reply, i spent so much time on this issue.

{"BaseUrl":"https://bingmapregistration.azurewebsites.net","RegistrationUrl":"https://bingmapregistration.azurewebsites.net/api/devices?nonce=10af3807-e6e5-b477-6e96-1b781c007536","RegistrationToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQW5vbnltb3VzIiwiaXNzIjoiUHJvamVjdEh1cmdoYWRhIiwianRpIjoiN2I0NTAzYmQtOTEzMS00ZDkxLWI1NzItNDNkYjNmODVkOTY3IiwiYXVkIjoiUmVnaXN0cmF0aW9uIiwiZXhwIjoiMTU0MjYwNzM4NyIsIm5iZiI6IjE1NDI2MDY0ODcifQ.nb-NN1vwQnbraf9wMrSMDdqmqycJRysrU8W05TRONYs";}

**Comment by Rasmi91** [comment]
I have installed androidclient.apk in my mobile to register the device.Issue solved
