### ISSUE TITLE
How to get barcode value to enter in mobile client

### ISSUE THREAD

**Issue by Rasmi91** [Microsoft/Bing-Maps-Fleet-Tracker#63]
When I was trying to run mobile client, it asking me to enter bar code value, Please let me know ,what value I have to give 

![issueimage](https://user-images.githubusercontent.com/42572707/47648527-485b6680-dba0-11e8-91d1-c87bc489e946.jpg)

**Comment by IoTGirl** [comment]
@Rasmi91 When you launch the app on your mobile device it will give you a QR code to register.  Reading the associated blog should clarify.  [https://blogs.bing.com/maps/2018-01/Announcing-the-Bing-Maps-Fleet-Tracker-Solution](https://blogs.bing.com/maps/2018-01/Announcing-the-Bing-Maps-Fleet-Tracker-Solution)

> Register devices for tracking by shooting a QR code or manually entering device information in the web application. The mobile companion app features client control of when location tracking is on or off, giving the mobile worker complete control of their location information
