### ISSUE TITLE
Operation: Write Deployments failed

### ISSUE THREAD

**Issue by vivek2391** [Microsoft/Bing-Maps-Fleet-Tracker#64]
I have used the Bing Maps Fleet Tracker Deployment portal to deploy the Bing Maps Feelt tracker solution into my Azure subscription. 

The deployment was not successful. In azure activity log, I see that "Write Resourcegroups" operation is successful but "write deployments" failed. Here is the summary of that failed operation:
![image](https://user-images.githubusercontent.com/44757737/48520529-f05a7a80-e896-11e8-9d20-e24a1aa30586.png)

**Comment by momohs** [comment]
I'm assuming this issue is resolved by now. Please feel free to reopen if you're still facing this issue.
