### ISSUE TITLE
Trips are not populating eventhough im having pipeline functions in azure function app

### ISSUE THREAD

**Issue by Rasmi91** [Microsoft/Bing-Maps-Fleet-Tracker#65]
Hi

My device is linked to my asset
I can able to see my device current location and data points of my trips
I'm having pipeline initiator,executor functions in my azure function app .
No errors found in log files.
- I havent used mobileclient project . Instead of this i have installed mobileclient.apk in my mobile to register the device.

- The problem is ,I cant able to see my trips.My trip legs & trips tables are empty. Please help me how to solve this?

**Comment by momohs** [comment]
I'm assuming that this issue is resolved by now. Please feel free to reopen if you're still facing the same issue.
