### ISSUE TITLE
AADSTS50011: The reply url specified in the request does not match the reply urls

### ISSUE THREAD

**Issue by mfritzgh** [Microsoft/Bing-Maps-Fleet-Tracker#66]
I'm getting this error when I attempt to start https://bmft.azurewebsites.net. I'm a c# client/server guy who knows next to nothing about websites so, no surprise, I have not been able to apply the suggestions I've found online to my azure site. Can you walk me thru it? Thanks!

AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: 'fd0b9734-3ea3-4811-8bbd-62a239519535'.

**Comment by momohs** [comment]
In the [deployment documentation](https://github.com/Microsoft/Bing-Maps-Fleet-Tracker/blob/master/DEPLOYMENT.md#creating-a-new-deployment), there are steps for creating and setting up the authorization application. It appears to me as if you need to make sure you did this step 

> Enter the Redirect Url as "https://{YOUR_DEPLOYMENT_NAME}.azurewebsites.net/signin-oidc"

**Comment by mfritzgh** [comment]
Thanks, Mohamed. I did see and try that step but clearly did something wrong because whatever string I was trying to apply as the 'reply url' was not accepted as valid.

I will retrace my steps and try again.
Thanks ! Matt


________________________________
