### ISSUE TITLE
Deployment URL is down

### ISSUE THREAD

**Issue by Ankeetshkk** [microsoft/Bing-Maps-Fleet-Tracker#78]
Team,

The Deployment URL is down from couple of days can you please check and let me know if there is any New URL been updated for this solution?

https://bingmapsfleettracker.azurewebsites.net/

Thank you

**Comment by momohs** [comment]
@Ankeetshkk I tried it and the page is up now. Please re-check it and re-open this issue if you're still facing an issue.
